const translations = {
    en: {
      'home': 'home',
      'docs': 'docs',
      'about': 'about',
      'hero-main': 'Trim,&thinsp;assemble,&thinsp;align:<br class="hidden sm:inline">all&thinsp;in&thinsp;one&thinsp;app',
      'hero-sec': 'Forget about cumbersome workflows <br class="hidden sm:inline"> with multiple tools',
      'hero-cta1': 'Donwload Now',  
      'hero-cta2': 'Know More',
      'features-title': 'Simplify&emsp;and&emsp;Customize&emsp;Your&emsp;Workflow',
      'feature-first-title': 'Automatic or Manual, you choose',
      'feature-first-text': 'You can set the Phred Score and the number of bases, or simply let t&a-Seq do it for you',
      'feature-second-title': 'Supports several ab1 formats',
      'feature-second-text': 'Not all ab1 files have the same structure, but t&a-Seq is able to deal with most of them',
      'feature-third-title': 'Free & Open Source',
      'feature-third-text': 'You only need to cite the paper to support the project, but your contributions are also appreciated!',
      'features-btn': 'View it in action',
      'testimonials-title': 'What our users think about t&a-Seq',
      'footer-app-description':'An app for easy analysis of Sanger sequences developed by researchers of the Autonomous Metropolitan University – Mexico.',
      'footer-enlace-github': 'GitHub Repository',
      'footer-credits': 'Website Design & Development by Carlos Pérez Cerón',
      'footer-update': 'Last Updated: November 2025'
    },
    es: {
      'home': 'inicio',
      'docs': 'documentación',
      'about': 'acerca de',
      'hero-main': 'Recorta,&thinsp;ensambla&thinsp;y&thinsp;alinea:<br class="hidden sm:inline">todo&thinsp;en&thinsp;una&thinsp;sola&thinsp;app',
      'hero-sec': 'Deja atrás los flujos de trabajo complicados <br class="hidden sm:inline"> con múltiples herramientas',
      'hero-cta1': 'Descarga la app',
      'hero-cta2': 'Saber más',
      'features-title': 'Simplifica&emsp;y&emsp;personaliza&emsp;el&emsp;análisis',
      'feature-first-title': 'Autómatico o manual: tú eliges',
      'feature-first-text': 'Puedes especificar el puntaje Phred y el número de bases, o bien, deja que t&a-seq lo haga por ti',
      'feature-second-title': 'Admite diversos formatos ab1',
      'feature-second-text': 'No todos los archivos ab1 tienen la misma estructura, pero t&a-seq puede procesar la mayoría de ellos',
      'feature-third-title': 'Gratuito y de código abierto',
      'feature-third-text': 'Basta con citar el artículo de investigación, pero tus contribuciones al repositorio son bienvenidas',
      'features-btn': 'Velo en acción',
      'testimonials-title': 'Conoce la opinión de quienes ya han usado t&a-Seq',
      'footer-app-description':'Una app para facilitar el análisis de secuencias Sanger desarrollada por investigadores de la Universidad Autónoma Metropolitana.',
      'footer-enlace-github': 'Repositorio GitHub',
      'footer-credits': 'Diseño y desarrollo de sitio por Carlos Pérez Cerón',
      'footer-update': 'Última actualización: Noviembre 2025'
    }
}